name: Check PR Author

on:
  pull_request:

jobs:
  check-author-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch pull request author
      id: pr-author
      run: |
        echo "Fetching PR author..."
        PR_AUTHOR=$(jq -r .pull_request.user.login < $GITHUB_EVENT_PATH)
        echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV
        echo "PR_AUTHOR is $PR_AUTHOR"

    - name: Validate PR Author
      id: validate-author
      run: |
        echo "Validating PR author against approved authors list..."
        APPROVED_AUTHORS=$(cat .github/AUTHORS)
        if echo "$APPROVED_AUTHORS" | grep -qw "$PR_AUTHOR"; then
          echo "$PR_AUTHOR is an approved author."
          echo "AUTHORIZATION=Authorized" >> $GITHUB_ENV
        else
          echo "ERROR: $PR_AUTHOR is not an approved author."
          echo "AUTHORIZATION=Unauthorized" >> $GITHUB_ENV
          exit 1
        fi